#!/usr/bin/env python
import sys
import json
from typing import Dict, Any


payload = sys.argv[1]


def jsonrpc_response(data: Dict[str, Any], error: bool = False) -> Dict[str, Any]:
    out = {
        'id': None,
        'jsonrpc': '2.0'
    }

    if error:
        out['error'] = data
    else:
        out['result'] = data

    return out


def ping(data: Dict[str, Any]) -> Dict[str, Any]:
    return {'message': 'OK'}


ref = {
    'ping': ping
}


if __name__ == '__main__':
    data = json.loads(payload)

    res = ref[data['method']](data['params'])

    print(json.dumps(res))
